In [2]:
import numpy as np
import pandas as pd

In [3]:
table_06 = pd.read_csv("table_06.csv", header=None)
table_06

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,14,12,1,2,8,17,7,0,9,18,4,19,15,3,13,10,11,6,16,5
1,13,12,11,0,15,10,5,4,16,17,7,18,19,2,8,1,6,3,14,9
2,17,12,19,8,11,1,5,0,16,3,15,6,13,10,9,2,18,14,4,7
3,18,6,7,19,13,0,4,10,9,17,16,14,2,8,1,5,15,12,3,11
4,6,0,16,14,3,4,11,2,10,18,15,17,5,9,13,19,1,8,7,12
5,17,9,11,10,7,3,5,8,16,4,18,13,15,0,19,1,14,12,2,6
6,7,18,15,10,11,8,9,13,1,14,4,2,17,12,3,5,6,19,0,16
7,11,10,14,19,8,1,4,5,7,16,12,9,0,2,6,17,18,3,15,13
8,11,7,3,1,19,10,9,6,4,12,0,15,18,14,5,8,13,16,17,2
9,3,16,15,13,19,18,11,1,9,2,8,10,4,14,6,17,12,5,7,0
10,15,9,3,18,8,10,5,14,6,0,16,12,2,19,13,11,7,4,17,1
11,6,4,19,12,15,17,10,14,3,11,18,8,7,9,2,13,0,1,5,16
12,19,13,18,1,10,3,9,2,17,14,12,7,16,15,0,6,11,4,5,8
13,12,18,3,17,11,15,9,6,14,1,4,13,2,0,16,8,19,7,5,10
14,11,19,18,16,2,12,4,15,1,6,7,5,13,9,17,0,8,3,14,10
15,2,10,4,14,7,19,18,3,15,11,17,0,6,9,5,1,13,12,16,8
16,6,10,3,9,13,7,16,19,5,18,4,17,11,15,8,2,1,14,12,0
17,17,12,7,11,15,13,18,3,0,4,19,9,8,2,16,1,6,10,5,14
18,10,5,9,2,13,19,1,15,6,16,3,18,17,11,8,12,14,4,0,7
19,5,2,18,11,10,17,15,1,12,19,14,0,4,3,7,9,6,8,16,13

In [4]:
prob_06 = pd.read_csv("prob_06.csv", header=None)
prob_06

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.24,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04
1,0.24,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04

**1. P(C) (6)**

In [5]:
def ciphertext_probability(C):
    C_probability = 0
    pairs_of_indexes = []
    
    for prob_M in range(len(prob_06.iloc[0])):
        for prob_K in range(len(prob_06.iloc[1])):
            if table_06.iloc[prob_M, prob_K] == C: # C = 0...19
                pairs = []
                pairs.append(prob_K)
                pairs.append(prob_M)
                pairs_of_indexes.append(pairs)
    
    for i in range(len(pairs_of_indexes)):
        C_probability += prob_06.iloc[0, pairs_of_indexes[i][0]] * prob_06.iloc[1, pairs_of_indexes[i][1]]
    
    return round(C_probability, 4)


C_prob = []
for C in range(20):
    C_prob.append(ciphertext_probability(C))

In [6]:
C_distribution = pd.DataFrame(C_prob).T
C_distribution

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.04,0.04,0.048,0.048,0.04,0.048,0.064,0.048,0.04,0.04,0.048,0.064,0.048,0.048,0.088,0.048,0.04,0.064,0.048,0.048

In [7]:
check_sum = 0
for i in range(len(C_distribution.iloc[0])):
    check_sum += C_distribution.iloc[0, i]

print(check_sum)

1.0000000000000002

**2. P(M,C) (6)**

In [8]:
def joint_probability_MC(C, t):
    res = []
    
    for j in range(len(table_06.iloc[0])):
        if table_06.iloc[j, t] == C:
            res.append(prob_06.iloc[1, j] * prob_06.iloc[0, t])

    return sum(res)

MC_prob = []
r = []
for t in range(20):
    for C in range(20):
        MC_prob.append(joint_probability_MC(C, t))
    
        r.append(MC_prob)

In [9]:
l = []
l.append(r[0][0:20])
l.append(r[0][20:40])
l.append(r[0][40:60])
l.append(r[0][60:80])
l.append(r[0][80:100])
l.append(r[0][100:120])
l.append(r[0][120:140])
l.append(r[0][140:160])
l.append(r[0][160:180])
l.append(r[0][180:200])
l.append(r[0][200:220])
l.append(r[0][220:240])
l.append(r[0][240:260])
l.append(r[0][260:280])
l.append(r[0][280:300])
l.append(r[0][300:320])
l.append(r[0][320:340])
l.append(r[0][340:360])
l.append(r[0][360:380])
l.append(r[0][380:400])

In [10]:
d = pd.DataFrame(l)
d

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0000,0.0000,0.0096,0.0096,0.0000,0.0096,0.0288,0.0096,0.0000,0.0000,0.0096,0.0288,0.0096,0.0096,0.0576,0.0096,0.0000,0.0288,0.0096,0.0096
1,0.0016,0.0000,0.0016,0.0000,0.0016,0.0016,0.0016,0.0016,0.0000,0.0032,0.0048,0.0000,0.0144,0.0016,0.0000,0.0000,0.0016,0.0000,0.0032,0.0016
2,0.0000,0.0096,0.0000,0.0064,0.0016,0.0000,0.0000,0.0032,0.0000,0.0016,0.0000,0.0032,0.0000,0.0000,0.0016,0.0032,0.0016,0.0000,0.0048,0.0032
3,0.0016,0.0032,0.0112,0.0000,0.0000,0.0000,0.0000,0.0000,0.0016,0.0016,0.0032,0.0032,0.0016,0.0016,0.0032,0.0000,0.0016,0.0016,0.0016,0.0032
4,0.0000,0.0000,0.0016,0.0016,0.0000,0.0000,0.0000,0.0032,0.0128,0.0000,0.0032,0.0048,0.0000,0.0048,0.0000,0.0048,0.0000,0.0000,0.0000,0.0032
5,0.0016,0.0032,0.0000,0.0032,0.0016,0.0000,0.0000,0.0016,0.0016,0.0000,0.0048,0.0000,0.0016,0.0016,0.0000,0.0016,0.0000,0.0128,0.0016,0.0032
6,0.0000,0.0016,0.0000,0.0000,0.0048,0.0064,0.0000,0.0096,0.0000,0.0064,0.0016,0.0032,0.0000,0.0000,0.0000,0.0016,0.0016,0.0000,0.0032,0.0000
7,0.0112,0.0032,0.0032,0.0032,0.0016,0.0016,0.0032,0.0000,0.0016,0.0000,0.0016,0.0000,0.0000,0.0016,0.0032,0.0032,0.0000,0.0000,0.0000,0.0016
8,0.0016,0.0032,0.0000,0.0016,0.0016,0.0016,0.0032,0.0016,0.0000,0.0128,0.0016,0.0000,0.0016,0.0000,0.0016,0.0016,0.0048,0.0016,0.0000,0.0000
9,0.0016,0.0016,0.0016,0.0016,0.0032,0.0000,0.0016,0.0000,0.0000,0.0000,0.0000,0.0032,0.0016,0.0000,0.0032,0.0000,0.0032,0.0032,0.0128,0.0016
10,0.0016,0.0000,0.0000,0.0016,0.0144,0.0000,0.0000,0.0032,0.0016,0.0000,0.0000,0.0000,0.0032,0.0000,0.0016,0.0032,0.0032,0.0016,0.0032,0.0016
11,0.0032,0.0000,0.0016,0.0000,0.0000,0.0016,0.0016,0.0016,0.0016,0.0032,0.0016,0.0000,0.0016,0.0032,0.0016,0.0016,0.0000,0.0032,0.0032,0.0096
12,0.0016,0.0000,0.0048,0.0000,0.0032,0.0016,0.0016,0.0016,0.0016,0.0000,0.0000,0.0016,0.0000,0.0032,0.0000,0.0112,0.0016,0.0032,0.0016,0.0016
13,0.0032,0.0000,0.0048,0.0112,0.0000,0.0000,0.0000,0.0000,0.0016,0.0064,0.0016,0.0016,0.0016,0.0000,0.0032,0.0032,0.0000,0.0000,0.0000,0.0016
14,0.0016,0.0016,0.0016,0.0016,0.0000,0.0032,0.0032,0.0016,0.0048,0.0016,0.0000,0.0000,0.0000,0.0128,0.0000,0.0000,0.0032,0.0016,0.0000,0.0016
15,0.0016,0.0064,0.0032,0.0000,0.0000,0.0032,0.0016,0.0000,0.0032,0.0016,0.0096,0.0016,0.0016,0.0016,0.0000,0.0000,0.0000,0.0032,0.0000,0.0016
16,0.0016,0.0032,0.0000,0.0000,0.0000,0.0000,0.0064,0.0016,0.0016,0.0000,0.0000,0.0112,0.0016,0.0032,0.0032,0.0016,0.0000,0.0000,0.0032,0.0016
17,0.0000,0.0016,0.0000,0.0048,0.0048,0.0016,0.0096,0.0016,0.0032,0.0000,0.0016,0.0000,0.0048,0.0000,0.0032,0.0000,0.0016,0.0000,0.0000,0.0016
18,0.0032,0.0000,0.0016,0.0016,0.0016,0.0064,0.0000,0.0032,0.0000,0.0000,0.0000,0.0000,0.0016,0.0000,0.0032,0.0016,0.0128,0.0032,0.0000,0.0000
19,0.0032,0.0016,0.0016,0.0000,0.0000,0.0096,0.0016,0.0032,0.0032,0.0016,0.0032,0.0016,0.0016,0.0032,0.0016,0.0000,0.0032,0.0000,0.0000,0.0000